### ISSUE TITLE
how to electron 

### ISSUE THREAD

**Issue by furfury** [awesome-arjun11/splitune#1]
Hello its is possible  for you to explain how to this the electron part please.

Cump,

**Comment by awesome-arjun11** [comment]
From what I understand you want to know how to configure and run the electron part of the app.


- Download and install [Node](https://nodejs.org/en/download/)
- To install dependencies run `npm install` from ***splitune*** project directory.

Further for python dependencies 

- run `pip install -r requirements.txt`

**Comment by furfury** [comment]
i get with screen on after electron build
